name: C CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build
        run: make -j
      - name: Run tests
        run: make test
